# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blackjackBotMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 936)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcd_n_generations = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_n_generations.setMinimumSize(QtCore.QSize(100, 0))
        self.lcd_n_generations.setDigitCount(10)
        self.lcd_n_generations.setProperty("intValue", 0)
        self.lcd_n_generations.setObjectName("lcd_n_generations")
        self.horizontalLayout.addWidget(self.lcd_n_generations)
        self.btn_play = QtWidgets.QToolButton(self.centralwidget)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_pause = QtWidgets.QToolButton(self.centralwidget)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout.addWidget(self.btn_pause)
        self.btn_step = QtWidgets.QToolButton(self.centralwidget)
        self.btn_step.setObjectName("btn_step")
        self.horizontalLayout.addWidget(self.btn_step)
        self.btn_step_round = QtWidgets.QToolButton(self.centralwidget)
        self.btn_step_round.setObjectName("btn_step_round")
        self.horizontalLayout.addWidget(self.btn_step_round)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinbox_n_games = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox_n_games.setMaximum(1000)
        self.spinbox_n_games.setProperty("value", 1)
        self.spinbox_n_games.setObjectName("spinbox_n_games")
        self.horizontalLayout.addWidget(self.spinbox_n_games)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.board_box = QtWidgets.QGroupBox(self.centralwidget)
        self.board_box.setMinimumSize(QtCore.QSize(0, 225))
        self.board_box.setObjectName("board_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.board_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hlayout_dealers_hand = QtWidgets.QHBoxLayout()
        self.hlayout_dealers_hand.setObjectName("hlayout_dealers_hand")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout_dealers_hand.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.hlayout_dealers_hand)
        self.hlayout_players_hand = QtWidgets.QHBoxLayout()
        self.hlayout_players_hand.setObjectName("hlayout_players_hand")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout_players_hand.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.hlayout_players_hand)
        self.verticalLayout.addWidget(self.board_box)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.progress_form = QtWidgets.QFormLayout()
        self.progress_form.setObjectName("progress_form")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.progress_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.progressBar_simulated = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_simulated.setMaximum(100)
        self.progressBar_simulated.setProperty("value", 0)
        self.progressBar_simulated.setObjectName("progressBar_simulated")
        self.progress_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.progressBar_simulated)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.progress_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.progressBar_generated = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_generated.setMaximum(100)
        self.progressBar_generated.setProperty("value", 0)
        self.progressBar_generated.setObjectName("progressBar_generated")
        self.progress_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.progressBar_generated)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.progress_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.progressBar_deck = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_deck.setProperty("value", 0)
        self.progressBar_deck.setObjectName("progressBar_deck")
        self.progress_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.progressBar_deck)
        self.verticalLayout.addLayout(self.progress_form)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.form_data_0 = QtWidgets.QFormLayout()
        self.form_data_0.setObjectName("form_data_0")
        self.labelNBots = QtWidgets.QLabel(self.groupBox)
        self.labelNBots.setObjectName("labelNBots")
        self.form_data_0.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelNBots)
        self.printNBots = QtWidgets.QLabel(self.groupBox)
        self.printNBots.setObjectName("printNBots")
        self.form_data_0.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.printNBots)
        self.labelNThreads = QtWidgets.QLabel(self.groupBox)
        self.labelNThreads.setObjectName("labelNThreads")
        self.form_data_0.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelNThreads)
        self.printNThreads = QtWidgets.QLabel(self.groupBox)
        self.printNThreads.setObjectName("printNThreads")
        self.form_data_0.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.printNThreads)
        self.labelNDecks = QtWidgets.QLabel(self.groupBox)
        self.labelNDecks.setObjectName("labelNDecks")
        self.form_data_0.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelNDecks)
        self.printNDecks = QtWidgets.QLabel(self.groupBox)
        self.printNDecks.setObjectName("printNDecks")
        self.form_data_0.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.printNDecks)
        self.labelNGamesPerGen = QtWidgets.QLabel(self.groupBox)
        self.labelNGamesPerGen.setObjectName("labelNGamesPerGen")
        self.form_data_0.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelNGamesPerGen)
        self.printNGamesPerGen = QtWidgets.QLabel(self.groupBox)
        self.printNGamesPerGen.setObjectName("printNGamesPerGen")
        self.form_data_0.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.printNGamesPerGen)
        self.verticalLayout_3.addLayout(self.form_data_0)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.form_data_1 = QtWidgets.QFormLayout()
        self.form_data_1.setObjectName("form_data_1")
        self.labelTGen = QtWidgets.QLabel(self.groupBox_2)
        self.labelTGen.setObjectName("labelTGen")
        self.form_data_1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTGen)
        self.printTGen = QtWidgets.QLabel(self.groupBox_2)
        self.printTGen.setObjectName("printTGen")
        self.form_data_1.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.printTGen)
        self.labelTGame = QtWidgets.QLabel(self.groupBox_2)
        self.labelTGame.setObjectName("labelTGame")
        self.form_data_1.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelTGame)
        self.printTGame = QtWidgets.QLabel(self.groupBox_2)
        self.printTGame.setObjectName("printTGame")
        self.form_data_1.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.printTGame)
        self.verticalLayout_4.addLayout(self.form_data_1)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.form_data_2 = QtWidgets.QFormLayout()
        self.form_data_2.setObjectName("form_data_2")
        self.labelBestAge = QtWidgets.QLabel(self.groupBox_3)
        self.labelBestAge.setObjectName("labelBestAge")
        self.form_data_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelBestAge)
        self.printBestAge = QtWidgets.QLabel(self.groupBox_3)
        self.printBestAge.setObjectName("printBestAge")
        self.form_data_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.printBestAge)
        self.labelBestDelta = QtWidgets.QLabel(self.groupBox_3)
        self.labelBestDelta.setObjectName("labelBestDelta")
        self.form_data_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelBestDelta)
        self.printBestDelta = QtWidgets.QLabel(self.groupBox_3)
        self.printBestDelta.setObjectName("printBestDelta")
        self.form_data_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.printBestDelta)
        self.verticalLayout_5.addLayout(self.form_data_2)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSimulation = QtWidgets.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionPrintBestBot = QtWidgets.QAction(MainWindow)
        self.actionPrintBestBot.setObjectName("actionPrintBestBot")
        self.menuSimulation.addAction(self.actionReset)
        self.menuSimulation.addAction(self.actionPrintBestBot)
        self.menubar.addAction(self.menuSimulation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Blackjack Bot"))
        self.btn_play.setText(_translate("MainWindow", "Play"))
        self.btn_pause.setText(_translate("MainWindow", "Pause"))
        self.btn_step.setText(_translate("MainWindow", "Step"))
        self.btn_step_round.setText(_translate("MainWindow", "Finish Game"))
        self.label_2.setText(_translate("MainWindow", "Step N Games"))
        self.board_box.setTitle(_translate("MainWindow", "Game"))
        self.label.setText(_translate("MainWindow", "Games Simulated"))
        self.label_5.setText(_translate("MainWindow", "Games Generated"))
        self.label_3.setText(_translate("MainWindow", "Deck Progress"))
        self.groupBox.setTitle(_translate("MainWindow", "Simulation"))
        self.labelNBots.setText(_translate("MainWindow", "N Bots"))
        self.printNBots.setText(_translate("MainWindow", "TextLabel"))
        self.labelNThreads.setText(_translate("MainWindow", "N Threads"))
        self.printNThreads.setText(_translate("MainWindow", "TextLabel"))
        self.labelNDecks.setText(_translate("MainWindow", "N Decks"))
        self.printNDecks.setText(_translate("MainWindow", "TextLabel"))
        self.labelNGamesPerGen.setText(_translate("MainWindow", "N Games / Gen"))
        self.printNGamesPerGen.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sim Stress"))
        self.labelTGen.setText(_translate("MainWindow", "Time / Gen"))
        self.printTGen.setText(_translate("MainWindow", "TextLabel"))
        self.labelTGame.setText(_translate("MainWindow", "Time / Game"))
        self.printTGame.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Best Bot"))
        self.labelBestAge.setText(_translate("MainWindow", "Age"))
        self.printBestAge.setText(_translate("MainWindow", "TextLabel"))
        self.labelBestDelta.setText(_translate("MainWindow", "Delta Median"))
        self.printBestDelta.setText(_translate("MainWindow", "TextLabel"))
        self.menuSimulation.setTitle(_translate("MainWindow", "Simulation"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionPrintBestBot.setText(_translate("MainWindow", "Print Best Bot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
