# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blackjackBotMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 1054)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcd_n_games = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_n_games.setMinimumSize(QtCore.QSize(100, 0))
        self.lcd_n_games.setDigitCount(10)
        self.lcd_n_games.setProperty("intValue", 0)
        self.lcd_n_games.setObjectName("lcd_n_games")
        self.horizontalLayout.addWidget(self.lcd_n_games)
        self.btn_play = QtWidgets.QToolButton(self.centralwidget)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_pause = QtWidgets.QToolButton(self.centralwidget)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout.addWidget(self.btn_pause)
        self.btn_step = QtWidgets.QToolButton(self.centralwidget)
        self.btn_step.setObjectName("btn_step")
        self.horizontalLayout.addWidget(self.btn_step)
        self.btn_step_round = QtWidgets.QToolButton(self.centralwidget)
        self.btn_step_round.setObjectName("btn_step_round")
        self.horizontalLayout.addWidget(self.btn_step_round)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinbox_n_games = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox_n_games.setMaximum(1000)
        self.spinbox_n_games.setProperty("value", 1)
        self.spinbox_n_games.setObjectName("spinbox_n_games")
        self.horizontalLayout.addWidget(self.spinbox_n_games)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.board_box = QtWidgets.QGroupBox(self.centralwidget)
        self.board_box.setMinimumSize(QtCore.QSize(0, 200))
        self.board_box.setObjectName("board_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.board_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hlayout_dealers_hand = QtWidgets.QHBoxLayout()
        self.hlayout_dealers_hand.setObjectName("hlayout_dealers_hand")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout_dealers_hand.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.hlayout_dealers_hand)
        self.hlayout_players_hand = QtWidgets.QHBoxLayout()
        self.hlayout_players_hand.setObjectName("hlayout_players_hand")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout_players_hand.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.hlayout_players_hand)
        self.verticalLayout.addWidget(self.board_box)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.progress_form = QtWidgets.QFormLayout()
        self.progress_form.setObjectName("progress_form")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.progress_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.progressBar_bots = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_bots.setMaximum(100)
        self.progressBar_bots.setProperty("value", 0)
        self.progressBar_bots.setObjectName("progressBar_bots")
        self.progress_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.progressBar_bots)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.progress_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.progressBar_generation = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_generation.setMaximum(100)
        self.progressBar_generation.setProperty("value", 0)
        self.progressBar_generation.setObjectName("progressBar_generation")
        self.progress_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.progressBar_generation)
        self.verticalLayout.addLayout(self.progress_form)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.form_data_0 = QtWidgets.QFormLayout()
        self.form_data_0.setObjectName("form_data_0")
        self.label_winners = QtWidgets.QLabel(self.centralwidget)
        self.label_winners.setObjectName("label_winners")
        self.form_data_0.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_winners)
        self.printNBots = QtWidgets.QLabel(self.centralwidget)
        self.printNBots.setObjectName("printNBots")
        self.form_data_0.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.printNBots)
        self.label_loosers = QtWidgets.QLabel(self.centralwidget)
        self.label_loosers.setObjectName("label_loosers")
        self.form_data_0.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_loosers)
        self.printNThreads = QtWidgets.QLabel(self.centralwidget)
        self.printNThreads.setObjectName("printNThreads")
        self.form_data_0.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.printNThreads)
        self.label_busters = QtWidgets.QLabel(self.centralwidget)
        self.label_busters.setObjectName("label_busters")
        self.form_data_0.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_busters)
        self.printNDecks = QtWidgets.QLabel(self.centralwidget)
        self.printNDecks.setObjectName("printNDecks")
        self.form_data_0.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.printNDecks)
        self.horizontalLayout_3.addLayout(self.form_data_0)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.form_data_1 = QtWidgets.QFormLayout()
        self.form_data_1.setObjectName("form_data_1")
        self.labelTGen = QtWidgets.QLabel(self.centralwidget)
        self.labelTGen.setObjectName("labelTGen")
        self.form_data_1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTGen)
        self.print_tb = QtWidgets.QLabel(self.centralwidget)
        self.print_tb.setObjectName("print_tb")
        self.form_data_1.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.print_tb)
        self.labelTGame = QtWidgets.QLabel(self.centralwidget)
        self.labelTGame.setObjectName("labelTGame")
        self.form_data_1.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelTGame)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.form_data_1.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.form_data_1.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.form_data_1.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.horizontalLayout_3.addLayout(self.form_data_1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.form_data_2 = QtWidgets.QFormLayout()
        self.form_data_2.setObjectName("form_data_2")
        self.labelBestMoney = QtWidgets.QLabel(self.centralwidget)
        self.labelBestMoney.setObjectName("labelBestMoney")
        self.form_data_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelBestMoney)
        self.print_best_money = QtWidgets.QLabel(self.centralwidget)
        self.print_best_money.setObjectName("print_best_money")
        self.form_data_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.print_best_money)
        self.horizontalLayout_3.addLayout(self.form_data_2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.form_data_3 = QtWidgets.QFormLayout()
        self.form_data_3.setObjectName("form_data_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.form_data_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.form_data_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.horizontalLayout_3.addLayout(self.form_data_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuSimulation = QtWidgets.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionPrintBestBot = QtWidgets.QAction(MainWindow)
        self.actionPrintBestBot.setObjectName("actionPrintBestBot")
        self.menuSimulation.addAction(self.actionReset)
        self.menuSimulation.addAction(self.actionPrintBestBot)
        self.menubar.addAction(self.menuSimulation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Blackjack Bot"))
        self.btn_play.setText(_translate("MainWindow", "Play"))
        self.btn_pause.setText(_translate("MainWindow", "Pause"))
        self.btn_step.setText(_translate("MainWindow", "Step"))
        self.btn_step_round.setText(_translate("MainWindow", "Finish Game"))
        self.label_2.setText(_translate("MainWindow", "Step N Games"))
        self.board_box.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "Bots"))
        self.label_5.setText(_translate("MainWindow", "Generation"))
        self.label_winners.setText(_translate("MainWindow", "N Bots"))
        self.printNBots.setText(_translate("MainWindow", "TextLabel"))
        self.label_loosers.setText(_translate("MainWindow", "N Threads"))
        self.printNThreads.setText(_translate("MainWindow", "TextLabel"))
        self.label_busters.setText(_translate("MainWindow", "N Decks"))
        self.printNDecks.setText(_translate("MainWindow", "TextLabel"))
        self.labelTGen.setText(_translate("MainWindow", "Time / Gen"))
        self.print_tb.setText(_translate("MainWindow", "TextLabel"))
        self.labelTGame.setText(_translate("MainWindow", "Time / Game"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.labelBestMoney.setText(_translate("MainWindow", "Best Money"))
        self.print_best_money.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.menuSimulation.setTitle(_translate("MainWindow", "Simulation"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionPrintBestBot.setText(_translate("MainWindow", "Print Best Bot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
